name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git history access

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use your preferred Python version

      - name: Install the project
        run: pip install .

      - name: Install pdoc
        run: pip install pdoc

      - name: Generate documentation
        run: |
          pdoc ./optimeo --logo logo.png --docformat numpy -o ./docs
          cp resources/logo.png ./docs/
          cp resources/logo.png ./docs/optimeo/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs  # Use the correct path where your docs are generated

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
